require 'rubygems'
require 'xmpp4r'
require 'xmpp4r/roster'
require 'eventmachine'
require 'evma_xmlpushparser'

require 'agent_xmpp/logger'
require 'agent_xmpp/parser'
require 'agent_xmpp/connection'
require 'agent_xmpp/client'
require 'agent_xmpp/roster'
